/**
 * DDL for the Phase 3 research store (SQLite).
 *
 * Conventions (binding, see lib/research-store/types.ts once it lands):
 * - All ids are TEXT primary keys.
 * - All timestamps are ISO-8601 TEXT, always injected by callers (nowIso), never
 *   generated by the database or by a clock inside this module.
 * - Probabilities are REAL fractions in [0, 1] with low <= mid <= high.
 *
 * This module contains DDL strings only — no database access, no side effects.
 */

/** Migration ledger: one row per applied migration version. */
export const SCHEMA_MIGRATIONS_DDL = `
CREATE TABLE IF NOT EXISTS schema_migrations (
  version INTEGER PRIMARY KEY,
  applied_at TEXT NOT NULL
);
`;

/** Human-curated sources attached to a market. Research input only — never a trade. */
export const MARKET_SOURCES_DDL = `
CREATE TABLE IF NOT EXISTS market_sources (
  id TEXT PRIMARY KEY,
  market_ticker TEXT NOT NULL,
  market_id TEXT NOT NULL,
  kind TEXT NOT NULL CHECK (kind IN (
    'official_resolution_source', 'supporting_source', 'news', 'forecast', 'data', 'other'
  )),
  title TEXT NOT NULL,
  url TEXT,
  publisher TEXT,
  excerpt TEXT,
  notes TEXT,
  credibility TEXT NOT NULL CHECK (credibility IN (
    'official', 'high', 'medium', 'low', 'unknown'
  )),
  status TEXT NOT NULL CHECK (status IN ('draft', 'accepted', 'rejected')),
  added_by TEXT NOT NULL CHECK (added_by IN ('human', 'fixture', 'ai_draft')),
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);
`;

export const MARKET_SOURCES_TICKER_INDEX_DDL = `
CREATE INDEX IF NOT EXISTS idx_market_sources_ticker ON market_sources (market_ticker);
`;

/** Manually entered research briefs. Human-typed content, never labeled AI research. */
export const RESEARCH_BRIEFS_DDL = `
CREATE TABLE IF NOT EXISTS research_briefs (
  id TEXT PRIMARY KEY,
  market_ticker TEXT NOT NULL,
  state TEXT NOT NULL CHECK (state IN (
    'not_run', 'insufficient_sources', 'draft', 'human_reviewed'
  )),
  summary TEXT,
  yes_case TEXT,
  no_case TEXT,
  key_evidence TEXT,
  uncertainties TEXT,
  missing_info TEXT,
  confidence TEXT NOT NULL CHECK (confidence IN ('low', 'medium', 'high')),
  source_count INTEGER NOT NULL CHECK (source_count >= 0),
  basis TEXT NOT NULL CHECK (basis IN (
    'manual', 'assembled_from_sources', 'ai_draft_unreviewed', 'fixture'
  )),
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);
`;

export const RESEARCH_BRIEFS_TICKER_INDEX_DDL = `
CREATE INDEX IF NOT EXISTS idx_research_briefs_ticker ON research_briefs (market_ticker);
`;

/**
 * Human-entered fair probability ranges. Fractions in [0, 1], ordered low <= mid <= high.
 * A fair probability is research input to the deterministic risk engine, never a verdict.
 */
export const PROBABILITY_ESTIMATES_DDL = `
CREATE TABLE IF NOT EXISTS probability_estimates (
  id TEXT PRIMARY KEY,
  market_ticker TEXT NOT NULL,
  low REAL NOT NULL CHECK (low >= 0.0 AND low <= 1.0),
  mid REAL NOT NULL CHECK (mid >= 0.0 AND mid <= 1.0),
  high REAL NOT NULL CHECK (high >= 0.0 AND high <= 1.0),
  rationale TEXT NOT NULL,
  basis TEXT NOT NULL CHECK (basis IN (
    'human_entered', 'human_reviewed', 'ai_suggested_unreviewed', 'fixture'
  )),
  confidence TEXT NOT NULL CHECK (confidence IN ('low', 'medium', 'high')),
  source_count INTEGER NOT NULL CHECK (source_count >= 0),
  brief_id TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  CHECK (low <= mid AND mid <= high)
);
`;

export const PROBABILITY_ESTIMATES_TICKER_INDEX_DDL = `
CREATE INDEX IF NOT EXISTS idx_probability_estimates_ticker
  ON probability_estimates (market_ticker);
`;

/**
 * Written theses. A ready thesis is required before PAPER_TRADE eligibility;
 * it never approves real trades. Archived rows remain as an audit trail.
 */
export const THESES_DDL = `
CREATE TABLE IF NOT EXISTS theses (
  id TEXT PRIMARY KEY,
  market_ticker TEXT NOT NULL,
  status TEXT NOT NULL CHECK (status IN ('draft', 'ready_for_risk', 'archived')),
  thesis TEXT NOT NULL,
  why_mispriced TEXT,
  invalidation_criteria TEXT,
  probability_estimate_id TEXT,
  source_ids_json TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);
`;

export const THESES_TICKER_INDEX_DDL = `
CREATE INDEX IF NOT EXISTS idx_theses_ticker ON theses (market_ticker);
`;

/**
 * Human-verified settlement-source records (Phase 4). Research sources never
 * satisfy the settlement-source risk check; only a record here with status
 * 'human_verified' counts as the resolution authority. authority_type is
 * nullable so drafts can be saved before the authority is chosen; the
 * validator requires it for 'human_verified'. No deletes: reject instead.
 */
export const MARKET_SETTLEMENT_SOURCES_DDL = `
CREATE TABLE IF NOT EXISTS market_settlement_sources (
  id TEXT PRIMARY KEY,
  market_ticker TEXT NOT NULL,
  market_id TEXT NOT NULL,
  title TEXT NOT NULL,
  url TEXT,
  publisher TEXT,
  authority_type TEXT CHECK (authority_type IN (
    'kalshi_rules', 'official_government_source', 'official_organization_source',
    'exchange_resolution_source', 'other'
  )),
  status TEXT NOT NULL CHECK (status IN ('draft', 'human_verified', 'rejected')),
  notes TEXT,
  verification_rationale TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);
`;

export const MARKET_SETTLEMENT_SOURCES_TICKER_INDEX_DDL = `
CREATE INDEX IF NOT EXISTS idx_market_settlement_sources_ticker
  ON market_settlement_sources (market_ticker);
`;

/**
 * Paper decision journal entries (Phase 4). Simulated decision snapshots
 * only: no stake, no contract count, no PnL, no lifecycle, no settlement
 * outcome. Created only from a server-validated PAPER_TRADE dossier; the
 * risk_verdict CHECK makes that the only storable verdict. Archived rows
 * remain as an audit trail. All probability-like columns are fractions in
 * [0, 1]; expected_edge is a fraction difference in [-1, 1].
 */
export const PAPER_DECISION_ENTRIES_DDL = `
CREATE TABLE IF NOT EXISTS paper_decision_entries (
  id TEXT PRIMARY KEY,
  market_ticker TEXT NOT NULL,
  market_id TEXT NOT NULL,
  market_title TEXT NOT NULL,
  platform TEXT NOT NULL,
  side TEXT NOT NULL CHECK (side IN ('YES')),
  paper_price REAL NOT NULL CHECK (paper_price >= 0.0 AND paper_price <= 1.0),
  implied_probability REAL NOT NULL
    CHECK (implied_probability >= 0.0 AND implied_probability <= 1.0),
  fair_low REAL NOT NULL CHECK (fair_low >= 0.0 AND fair_low <= 1.0),
  fair_mid REAL NOT NULL CHECK (fair_mid >= 0.0 AND fair_mid <= 1.0),
  fair_high REAL NOT NULL CHECK (fair_high >= 0.0 AND fair_high <= 1.0),
  expected_edge REAL NOT NULL CHECK (expected_edge >= -1.0 AND expected_edge <= 1.0),
  confidence TEXT NOT NULL CHECK (confidence IN ('low', 'medium', 'high')),
  thesis_id TEXT NOT NULL,
  thesis_snapshot TEXT NOT NULL,
  probability_estimate_id TEXT,
  research_source_ids_json TEXT,
  research_sources_snapshot_json TEXT,
  settlement_source_id TEXT NOT NULL,
  settlement_source_snapshot_json TEXT NOT NULL,
  risk_verdict TEXT NOT NULL CHECK (risk_verdict IN ('PAPER_TRADE')),
  risk_checklist_json TEXT NOT NULL,
  risk_reasons_json TEXT,
  market_snapshot_json TEXT,
  status TEXT NOT NULL CHECK (status IN ('logged', 'archived')),
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  CHECK (fair_low <= fair_mid AND fair_mid <= fair_high)
);
`;

export const PAPER_DECISION_ENTRIES_TICKER_INDEX_DDL = `
CREATE INDEX IF NOT EXISTS idx_paper_decision_entries_ticker
  ON paper_decision_entries (market_ticker);
`;

/**
 * Advisory AI research draft ledger (Phase 5). Drafts are generated copilot
 * artifacts that sit entirely outside the deterministic risk path: they never
 * satisfy a risk check, never promote sources, briefs, theses, or settlement
 * records, and never create paper entries. There are deliberately no verdict,
 * stake, size, or PnL-shaped columns. Archive-only lifecycle: no deletes and
 * no unarchive; archived rows remain as an audit trail.
 */
export const AI_RESEARCH_DRAFTS_DDL = `
CREATE TABLE IF NOT EXISTS ai_research_drafts (
  id TEXT PRIMARY KEY,
  market_ticker TEXT NOT NULL,
  market_id TEXT NOT NULL,
  draft_type TEXT NOT NULL CHECK (draft_type IN (
    'research_questions', 'source_checklist', 'brief_draft', 'thesis_critique',
    'missing_info', 'skeptical_countercase'
  )),
  status TEXT NOT NULL CHECK (status IN ('draft', 'archived')),
  provider TEXT NOT NULL,
  model TEXT NOT NULL,
  prompt_version TEXT NOT NULL,
  input_snapshot_json TEXT NOT NULL,
  output_markdown TEXT NOT NULL,
  output_json TEXT,
  user_focus TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);
`;

export const AI_RESEARCH_DRAFTS_TICKER_INDEX_DDL = `
CREATE INDEX IF NOT EXISTS idx_ai_research_drafts_ticker
  ON ai_research_drafts (market_ticker);
`;
