/**
 * DDL for the Phase 3 research store (SQLite).
 *
 * Conventions (binding, see lib/research-store/types.ts once it lands):
 * - All ids are TEXT primary keys.
 * - All timestamps are ISO-8601 TEXT, always injected by callers (nowIso), never
 *   generated by the database or by a clock inside this module.
 * - Probabilities are REAL fractions in [0, 1] with low <= mid <= high.
 *
 * This module contains DDL strings only — no database access, no side effects.
 */

/** Migration ledger: one row per applied migration version. */
export const SCHEMA_MIGRATIONS_DDL = `
CREATE TABLE IF NOT EXISTS schema_migrations (
  version INTEGER PRIMARY KEY,
  applied_at TEXT NOT NULL
);
`;

/** Human-curated sources attached to a market. Research input only — never a trade. */
export const MARKET_SOURCES_DDL = `
CREATE TABLE IF NOT EXISTS market_sources (
  id TEXT PRIMARY KEY,
  market_ticker TEXT NOT NULL,
  market_id TEXT NOT NULL,
  kind TEXT NOT NULL CHECK (kind IN (
    'official_resolution_source', 'supporting_source', 'news', 'forecast', 'data', 'other'
  )),
  title TEXT NOT NULL,
  url TEXT,
  publisher TEXT,
  excerpt TEXT,
  notes TEXT,
  credibility TEXT NOT NULL CHECK (credibility IN (
    'official', 'high', 'medium', 'low', 'unknown'
  )),
  status TEXT NOT NULL CHECK (status IN ('draft', 'accepted', 'rejected')),
  added_by TEXT NOT NULL CHECK (added_by IN ('human', 'fixture', 'ai_draft')),
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);
`;

export const MARKET_SOURCES_TICKER_INDEX_DDL = `
CREATE INDEX IF NOT EXISTS idx_market_sources_ticker ON market_sources (market_ticker);
`;

/** Manually entered research briefs. Human-typed content, never labeled AI research. */
export const RESEARCH_BRIEFS_DDL = `
CREATE TABLE IF NOT EXISTS research_briefs (
  id TEXT PRIMARY KEY,
  market_ticker TEXT NOT NULL,
  state TEXT NOT NULL CHECK (state IN (
    'not_run', 'insufficient_sources', 'draft', 'human_reviewed'
  )),
  summary TEXT,
  yes_case TEXT,
  no_case TEXT,
  key_evidence TEXT,
  uncertainties TEXT,
  missing_info TEXT,
  confidence TEXT NOT NULL CHECK (confidence IN ('low', 'medium', 'high')),
  source_count INTEGER NOT NULL CHECK (source_count >= 0),
  basis TEXT NOT NULL CHECK (basis IN (
    'manual', 'assembled_from_sources', 'ai_draft_unreviewed', 'fixture'
  )),
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);
`;

export const RESEARCH_BRIEFS_TICKER_INDEX_DDL = `
CREATE INDEX IF NOT EXISTS idx_research_briefs_ticker ON research_briefs (market_ticker);
`;

/**
 * Human-entered fair probability ranges. Fractions in [0, 1], ordered low <= mid <= high.
 * A fair probability is research input to the deterministic risk engine, never a verdict.
 */
export const PROBABILITY_ESTIMATES_DDL = `
CREATE TABLE IF NOT EXISTS probability_estimates (
  id TEXT PRIMARY KEY,
  market_ticker TEXT NOT NULL,
  low REAL NOT NULL CHECK (low >= 0.0 AND low <= 1.0),
  mid REAL NOT NULL CHECK (mid >= 0.0 AND mid <= 1.0),
  high REAL NOT NULL CHECK (high >= 0.0 AND high <= 1.0),
  rationale TEXT NOT NULL,
  basis TEXT NOT NULL CHECK (basis IN (
    'human_entered', 'human_reviewed', 'ai_suggested_unreviewed', 'fixture'
  )),
  confidence TEXT NOT NULL CHECK (confidence IN ('low', 'medium', 'high')),
  source_count INTEGER NOT NULL CHECK (source_count >= 0),
  brief_id TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  CHECK (low <= mid AND mid <= high)
);
`;

export const PROBABILITY_ESTIMATES_TICKER_INDEX_DDL = `
CREATE INDEX IF NOT EXISTS idx_probability_estimates_ticker
  ON probability_estimates (market_ticker);
`;

/**
 * Written theses. A ready thesis is required before PAPER_TRADE eligibility;
 * it never approves real trades. Archived rows remain as an audit trail.
 */
export const THESES_DDL = `
CREATE TABLE IF NOT EXISTS theses (
  id TEXT PRIMARY KEY,
  market_ticker TEXT NOT NULL,
  status TEXT NOT NULL CHECK (status IN ('draft', 'ready_for_risk', 'archived')),
  thesis TEXT NOT NULL,
  why_mispriced TEXT,
  invalidation_criteria TEXT,
  probability_estimate_id TEXT,
  source_ids_json TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);
`;

export const THESES_TICKER_INDEX_DDL = `
CREATE INDEX IF NOT EXISTS idx_theses_ticker ON theses (market_ticker);
`;
